# Generated by Django 4.2.4 on 2023-09-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0002_item_meal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='per_pound',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Per Pound')], default=0),
        ),
    ]
