# Generated by Django 4.2.4 on 2023-09-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0003_item_per_pound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='meal_type',
            field=models.CharField(choices=[('cold_items', 'Cold Items'), ('bbq_items', 'BBQ Items'), ('specials', 'Specials')], max_length=200),
        ),
    ]
